-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.contratante DROP CONSTRAINT IF EXISTS fk_id_usuario;

ALTER TABLE IF EXISTS public.freelancer DROP CONSTRAINT IF EXISTS fk_id_usuario;

ALTER TABLE IF EXISTS public.projeto DROP CONSTRAINT IF EXISTS fk_id_contratante;

ALTER TABLE IF EXISTS public.projeto DROP CONSTRAINT IF EXISTS fk_id_categoria;

ALTER TABLE IF EXISTS public.servico_prestado DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.servico_prestado DROP CONSTRAINT IF EXISTS None;



DROP TABLE IF EXISTS public.usuario;

CREATE TABLE IF NOT EXISTS public.usuario
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 ),
    usuario character varying(128)[] NOT NULL,
    senha character(64)[] NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.contratante;

CREATE TABLE IF NOT EXISTS public.contratante
(
    id_usuario integer NOT NULL,
    num_documento character varying(14)[] NOT NULL,
    CONSTRAINT pk_id_usuario_contratante PRIMARY KEY (id_usuario)
);

DROP TABLE IF EXISTS public.freelancer;

CREATE TABLE IF NOT EXISTS public.freelancer
(
    id_usuario integer NOT NULL,
    num_documento character varying(14)[] NOT NULL,
    data_nascimento date,
    descricao character varying(255)[],
    area_atuacao character varying(20)[],
    habilidades character varying(255)[],
    portfolio character varying(128)[],
    CONSTRAINT pk_id_usuario_freelancer PRIMARY KEY (id_usuario)
);

DROP TABLE IF EXISTS public.projeto;

CREATE TABLE IF NOT EXISTS public.projeto
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 ),
    titulo character varying(100)[],
    descricao character varying(255)[],
    id_categoria integer,
    prazo date,
    orcamento double precision,
    id_contratante integer NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.servico_prestado;

CREATE TABLE IF NOT EXISTS public.servico_prestado
(
    projeto_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 ),
    freelancer_id_usuario integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 ),
    concluido boolean,
    pagamento double precision
);

DROP TABLE IF EXISTS public.categoria;

CREATE TABLE IF NOT EXISTS public.categoria
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 ),
    nome character varying(128)[],
    descricao character varying(255)[],
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.contratante
    ADD CONSTRAINT fk_id_usuario FOREIGN KEY (id_usuario)
    REFERENCES public.usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.freelancer
    ADD CONSTRAINT fk_id_usuario FOREIGN KEY (id_usuario)
    REFERENCES public.usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.projeto
    ADD CONSTRAINT fk_id_contratante FOREIGN KEY (id_contratante)
    REFERENCES public.contratante (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.projeto
    ADD CONSTRAINT fk_id_categoria FOREIGN KEY (id_categoria)
    REFERENCES public.categoria (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.servico_prestado
    ADD FOREIGN KEY (projeto_id)
    REFERENCES public.projeto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.servico_prestado
    ADD FOREIGN KEY (freelancer_id_usuario)
    REFERENCES public.freelancer (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;